language: python
dist: trusty
sudo: required
services:
- docker
python:
- '3.6'

env:
  global:
  # sentry auth
  - secure: "NN53FLsPD7CvoiKxzWHjIY9PpILk67Xi0Y3cPCrZQLJr8nDCk8kdgj/L/PlAoH2/hCAW/xhmBz0XA10zEmeXdVYPpfGR1tIWdrRpakNNNvoaQSaMd3ILfU+g8oL0oYLFGHlIGYvlqf6XtJ6ZthGIiquxNkKGHKLV+4xWs980Xws/t6XZdkO/9A4fPt5uiNSj7GW3ofn540Cyqrud/dROWDhcwtTXcnbzscLHW+0++EUA4z9bBFwyeoDxtmC/nnI2bJxUY49yJ6+4cpVAZcsDrEWyGA7oTUPHi78NrffS8/GdsoXb75TtQczGXquNXTzCuf75QLTZyj4BIi3GI18sakHvjfswDv2JPLnXEW/OtIWcpym/uWSYkQucwmrZ4c0F9Fp70qMc+FQyBMqdoYSpXkKD/Ou7MDci0PGD4s8tOhkwBT1sLvKBqpsq8YQ0Tgt80Z871wbihiLYFQkdbBBzFLPiua8Gdw41WKcFRYIbial4rnau2Mk2dlXUHGJLZTtqvKva1Yf4SI+zNE0L2Ac97dZ/b1MFYq0A6cOz764lupHxrHsagSVX86f+tC55d/OZWz9/K3RQBqksS4LoDMMu/4a4dZJg786YE9JlWpk9wCZkj28PhiCmWe9kEmE9tHOJDSXNbiI3GGDuUn5itRSxpuTp/45BCxZwS68Hx54j1aA="
  # Docker username and password
  - secure: "BjN9fOnOc+P89XAVPQpp4sedQsqPCz0IRlqohcBvM+azf5XOWcZXIEQwKolNjO888/kylO/W6HQF0uzjZqjcNDX5fBS56rOX685ELlGba3I8022xDG2IIJr7Ihc8EtILgDXiQacdTIOwlZhiPGbEl1uueCY+CWhhx8y0t6FwUnfSi8xqymMY/mbVdEq2/xXhbL+wq0OvXPJUahUiLEeY89FQDMIysJPydw2G/TMsFPm2GbYF+YX+MDD3Wm1Jk6UoH68bgWX2zD9S/H9zZuaGJg91N4knrP1WuoekF9j1naESx5q5VBmJlSJ9RTPoCaiaEWpS482CFe2CyimCGdxmTzMXjQ1bWGgNyZ9c4ieBYAIBHYJH2VkBsQZzMNp3v2lJV47fLFlcXtSgKg8Obm5Z0NV9gNJ4Ky11nUkEcZzPKhhkflK+bxuovHEwe7Kpht+MKedlSZk4os2SQeJyzBR/t+V0SPciBqeZA13yANBfqCxnCM3UetKhMPSbM7pDGpsMlM21ThFCRpv3hwHG8d4z7e9vXPJKtj/Ai5N1SVdgCNMox/u4N00fFZrlTUbeDEDgC6wLjXORLh8rQey9U7xpfa91iZzxoLma1zDofdunB0rwVtJkyxt4QhEEAVv2KF//wnpxceHkLHPAvNlWDyh2ngFiwPzhO3F5tVdLjSUoqVY="
  - secure: "OYby5o4k2bQrH0EKrSUNynZoi2RpCXw632cATRb/adJkL2PzSKQ9HOQRLYj8Gx7OgpvuFvwh9ujqceRVIdwEn/sjh8PEnJaC+wu5TL32DVrvB+EH9IOYLTHX8nvWeMYaeUEccMsW1pGT+WKfuR3mEBkvhQOOis/H+gvmiR+G+PmIFdz1xAoX6KapsTpMXg1bnISVMeD6BZ4Wi7TsRH/DFw9Clx5tsZaUI+RJwPOXLj6BhRa9QzNqvKJ3KPSsL3keC06EBNgsXAEHWVjTk6ouOoXkO3ENgvqjqxCjqkTh//D8iMi0KhZQEB7RU0T0Iyf3AL6GornpUOYO97dnNNH0aU4FDE27tdFu1oAveRz0+EZ20YfVfnenj8uWWTeC1jjZVyJJ++b8IqDb1YVodjtxYLR86RwiUjsaLMWSB/KFZms8YW1FsYvcaL8HQpJNi1QkB3a/+db3JyrtjmLedUKOkJetsxfbS3WLnvYWCnM8NaHYdMgt0i6QPQ4Hu2Ja8Krjq+9EJ6RwQM+ZD9pdlRbGcfyvDIfvmraPceQ7anN9JDgJiq4neuK2CxNlypV4F6tCbDuOqB/FXLoh1JNa/FjHVIlsmNKMt0v6f9DMj8ZXYB739jNwYyELSdIn27mJOn9S+k/Bjk6T8K88SDy4s3zRNpr98k4yJs4MmivVqNx/6Wk="
  - FLASK_ENV=development


before_install:
- openssl aes-256-cbc -K $encrypted_0180fa854b5b_key -iv $encrypted_0180fa854b5b_iv -in deploy/ssh_key.enc -out /tmp/deploy_key -d
- openssl aes-256-cbc -K $encrypted_1287f26e886e_key -iv $encrypted_1287f26e886e_iv -in deploy/stage_key.enc -out /tmp/stage_key -d

install:
- pip install pipenv
- pipenv install --dev

before_script:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
- echo $PYTHONPATH
- export MODE=CI

script:
- nosetests tests --with-coverage

after_success:
- codecov
- echo $(pwd)

deploy:
- provider: script
  script: bash deploy/travis.sh
  on:
    python: '3.6'
    tags: true

notifications:
  slack:
    rooms:
    - secure: xsGLjigcoVbbQljrB91BZ5VnXchIr0oxEgvW5QiKnHUqMNLZYctD5Dl3eLis3U1nThPmspt0CbSuCag9QuFK+f36h8yBJtCAEVJvEYpt+BRTwWYiw9fBT8SgLmilVInwF1SH5u6Zr+KTRDR3QXOG7ZwpFUa6zZ3yYNbKGXyFGD0vLMnwgBqIdCEYmA4ryurvg6yngr6iTv9OctRqeGDWprlhyIrmP4lnn0SnGuks9zxW39AzX1234JM05ys4UwbMno0j5zlY+uECSYJkW/WV4UtSdJQeF6+2qcguveNswh1w+Otlts471hWRbPZfFHbCHJlnTM7x2HeG1IuLe8yhZHiwclxPtYPln5p4kTtgCON9gXNKpDSeXoAYJbPF2K5k9B/732GlKhilEqEnD06z281PezAZ8HmPaprFA4/fVFQQ9Yqvwk4SKNEh1SUfTBfYSMY0XZoXz/sZ898hJAV4GQ5ImEog1cZnFdD9kqJl1zIu+FSTtDY5PqfSUn+iFeEJbo6gBsPyKrdgNaN/1hvLnthudiSW+E1DNIF1nxZ/lA4dQdOp0tSCR3nj5XZMKgJgAyZAUD2mXGPZAJUamSnxHRzPFurD+54mqMcWFxLp3Y0lNuBdez5l9SjdH+ZagYpvdTZ1aeAEmVpvCgSrcb8voKmH4J2bFTHEQ1rdUQyD+tE=
    on_success: always # you can also set to `change`
    on_failure: always
