version: "3"
services:
  everyclass-server:
    image: everyclass-server:${CURRENT_VERSION}
    sysctls:
    - net.core.somaxconn=4096
    environment:
      MODE: DEVELOPMENT
    ports:
      - 5001:80